columns: 80
newline: lf

steps:

  - simple_align:
      cases: false
      top_level_patterns: false
      records: false

  - imports:
      align: none
      list_align: after_alias
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true

  - tabs:
      spaces: 4

  - trailing_whitespace: {}
